spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: debezium
    password: dbz
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: migration-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual # ?? ack ?? ??
    properties:
      spring.json.trusted.packages: '*'

logging:
  level:
    root: INFO
    org.springframework.kafka: DEBUG
